// Package infra holds the Postgres-backed implementation of the
// llm_provider domain. Queries are generated by sqlc — see queries.sql
// for the SQL surface; this file only owns the (de)serialisation between
// the generated row types and the domain model, plus the cryptobox
// sealing for api_key_encrypted.
//
// Encryption contract:
//   - CreateProvider / UpdateProvider treat the inbound Provider.ApiKey as
//     plaintext. Both methods seal it via the cryptobox before insert /
//     update. An empty ApiKey on UpdateProvider means "leave the stored
//     key unchanged".
//   - GetProviderByName / GetProviderByID / ListProviders return the
//     SEALED blob in Provider.ApiKey. It is the caller's job (the
//     llm_proxy) to decrypt; handlers in this module never surface the
//     field on the wire.
package infra

import (
	"context"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/hangrix/hangrix/apps/hangrix/internal/config"
	"github.com/hangrix/hangrix/apps/hangrix/internal/database"
	"github.com/hangrix/hangrix/apps/hangrix/internal/modules/llm_provider/domain"
	"github.com/hangrix/hangrix/apps/hangrix/internal/modules/llm_provider/infra/llmproviderdb"
	"github.com/hangrix/hangrix/pkg/cryptobox"
)

//go:embed migrations/*.sql
var migrationsFS embed.FS

// PostgresRepo implements domain.Repo and domain.Lookup on a single pgx
// pool. The module binds the same instance to both interfaces.
type PostgresRepo struct {
	q    *llmproviderdb.Queries
	pool *pgxpool.Pool
	box  *cryptobox.Box
}

type PostgresRepoDeps struct {
	Pool   *pgxpool.Pool
	Config *config.Config
}

// NewPostgresRepo applies migrations and constructs the cryptobox up front
// so a malformed master key fails loudly at startup instead of on the first
// CreateProvider call. Mirrors the fail-loud pattern of the other modules'
// migration runners.
func NewPostgresRepo(deps *PostgresRepoDeps) *PostgresRepo {
	sub, err := fs.Sub(migrationsFS, "migrations")
	if err != nil {
		panic(fmt.Errorf("llm_provider migrations sub-fs: %w", err))
	}
	if err := database.Migrate(deps.Pool, sub, "goose_llm_provider", "."); err != nil {
		panic(fmt.Errorf("apply llm_provider migrations: %w", err))
	}
	box, err := cryptobox.New(deps.Config.LLM.EncryptionKey)
	if err != nil {
		panic(fmt.Errorf("llm_provider cryptobox: %w", err))
	}
	return &PostgresRepo{
		q:    llmproviderdb.New(deps.Pool),
		pool: deps.Pool,
		box:  box,
	}
}

// ---- providers ----

// emptyStrings coalesces a nil slice to a non-nil empty slice so pgx encodes it
// as an empty SQL array ('{}') rather than NULL. The allowed_models column is
// NOT NULL; allowed_models itself is deprecated (no longer used for routing),
// but the column is retained, so writes must still satisfy the constraint.
func emptyStrings(s []string) []string {
	if s == nil {
		return []string{}
	}
	return s
}

func (r *PostgresRepo) CreateProvider(ctx context.Context, p *domain.Provider) (*domain.Provider, error) {
	sealed, err := r.box.Encrypt(p.ApiKey)
	if err != nil {
		return nil, fmt.Errorf("seal api key: %w", err)
	}
	row, err := r.q.CreateProvider(ctx, llmproviderdb.CreateProviderParams{
		Name:            p.Name,
		Type:            string(p.Type),
		BaseUrl:         p.BaseURL,
		ApiKeyEncrypted: sealed,
		AllowedModels:   emptyStrings(p.AllowedModels),
		ActorID:         p.ActorID,
	})
	if err != nil {
		if database.IsUniqueViolation(err) {
			return nil, domain.ErrProviderConflict
		}
		return nil, err
	}
	return providerFromRow(row), nil
}

func (r *PostgresRepo) UpdateProvider(ctx context.Context, p *domain.Provider) (*domain.Provider, error) {
	var sealedArg pgtype.Text
	if p.ApiKey != "" {
		s, err := r.box.Encrypt(p.ApiKey)
		if err != nil {
			return nil, fmt.Errorf("seal api key: %w", err)
		}
		sealedArg = pgtype.Text{String: s, Valid: true}
	}
	row, err := r.q.UpdateProvider(ctx, llmproviderdb.UpdateProviderParams{
		ID:              p.ID,
		BaseUrl:         p.BaseURL,
		ApiKeyEncrypted: sealedArg,
		AllowedModels:   emptyStrings(p.AllowedModels),
		Disabled:        p.Disabled,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrProviderNotFound
		}
		return nil, err
	}
	return providerFromRow(row), nil
}

func (r *PostgresRepo) GetProviderByName(ctx context.Context, name string) (*domain.Provider, error) {
	row, err := r.q.GetProviderByName(ctx, name)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrProviderNotFound
		}
		return nil, err
	}
	return providerFromRow(row), nil
}

func (r *PostgresRepo) GetProviderByID(ctx context.Context, id int64) (*domain.Provider, error) {
	row, err := r.q.GetProviderByID(ctx, id)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrProviderNotFound
		}
		return nil, err
	}
	return providerFromRow(row), nil
}

func (r *PostgresRepo) ListProviders(ctx context.Context) ([]*domain.Provider, error) {
	rows, err := r.q.ListProviders(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*domain.Provider, 0, len(rows))
	for _, row := range rows {
		out = append(out, providerFromRow(row))
	}
	return out, nil
}

// SetProviderDisabled flips the disabled flag without touching the rest of
// the row. Returns the updated provider (sealed key still opaque). The
// admin handler uses this as a one-call toggle so it doesn't have to read
// the row, mutate, and write it back.
func (r *PostgresRepo) SetProviderDisabled(ctx context.Context, id int64, disabled bool) (*domain.Provider, error) {
	row, err := r.q.SetProviderDisabled(ctx, llmproviderdb.SetProviderDisabledParams{
		ID:       id,
		Disabled: disabled,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrProviderNotFound
		}
		return nil, err
	}
	return providerFromRow(row), nil
}

func (r *PostgresRepo) DeleteProvider(ctx context.Context, id int64) error {
	n, err := r.q.DeleteProvider(ctx, id)
	if err != nil {
		return err
	}
	if n == 0 {
		return domain.ErrProviderNotFound
	}
	return nil
}

// ---- usage log ----

func (r *PostgresRepo) RecordUsage(ctx context.Context, u *domain.UsageRecord) error {
	var sessionArg pgtype.Int8
	if u.SessionID != nil {
		sessionArg = pgtype.Int8{Int64: *u.SessionID, Valid: true}
	}
	return r.q.RecordUsage(ctx, llmproviderdb.RecordUsageParams{
		SessionID:        sessionArg,
		ProviderID:       u.ProviderID,
		Model:            u.Model,
		PromptTokens:     u.PromptTokens,
		CompletionTokens: u.CompletionTokens,
		TotalTokens:      u.TotalTokens,
		LatencyMs:        u.LatencyMS,
		StatusCode:       u.StatusCode,
		ErrorMessage:     u.ErrorMessage,
		RequestPath:      u.RequestPath,
		RequestBody:      u.RequestBody,
		ResponseBody:     u.ResponseBody,
	})
}

// ListUsage is a read helper outside the Repo interface — the admin handler
// renders it; the proxy never calls it. since/limit/offset are clamped by
// the caller; offset paginates a window over the same filter set, and
// CountUsage exposes the matching total so the UI can render a page count.
func (r *PostgresRepo) ListUsage(ctx context.Context, providerID *int64, since *time.Time, offset, limit int) ([]*UsageRow, error) {
	provArg, sinceArg := usageFilterArgs(providerID, since)
	rows, err := r.q.ListUsage(ctx, llmproviderdb.ListUsageParams{
		ProviderID: provArg,
		Since:      sinceArg,
		Off:        int32(offset),
		Lim:        int32(limit),
	})
	if err != nil {
		return nil, err
	}
	out := make([]*UsageRow, 0, len(rows))
	for _, row := range rows {
		ur := &UsageRow{
			ID:               row.ID,
			ProviderID:       row.ProviderID,
			ProviderName:     row.ProviderName,
			Model:            row.Model,
			PromptTokens:     row.PromptTokens,
			CompletionTokens: row.CompletionTokens,
			TotalTokens:      row.TotalTokens,
			LatencyMS:        row.LatencyMs,
			StatusCode:       row.StatusCode,
			ErrorMessage:     row.ErrorMessage,
			RequestPath:      row.RequestPath,
			CreatedAt:        row.CreatedAt.Time,
		}
		if row.SessionID.Valid {
			v := row.SessionID.Int64
			ur.SessionID = &v
		}
		out = append(out, ur)
	}
	return out, nil
}

// CountUsage returns the row count matching the same filter set as
// ListUsage — the admin page pairs the two to drive its pager.
func (r *PostgresRepo) CountUsage(ctx context.Context, providerID *int64, since *time.Time) (int64, error) {
	provArg, sinceArg := usageFilterArgs(providerID, since)
	return r.q.CountUsage(ctx, llmproviderdb.CountUsageParams{
		ProviderID: provArg,
		Since:      sinceArg,
	})
}

func usageFilterArgs(providerID *int64, since *time.Time) (pgtype.Int8, pgtype.Timestamptz) {
	var (
		provArg  pgtype.Int8
		sinceArg pgtype.Timestamptz
	)
	if providerID != nil {
		provArg = pgtype.Int8{Int64: *providerID, Valid: true}
	}
	if since != nil {
		sinceArg = pgtype.Timestamptz{Time: *since, Valid: true}
	}
	return provArg, sinceArg
}

// UsageRow is the read-side projection returned by ListUsage. It mirrors
// domain.UsageRecord plus a denormalized provider name for display and the
// row id/timestamp the writer never sees.
type UsageRow struct {
	ID               int64
	SessionID        *int64
	ProviderID       int64
	ProviderName     string
	Model            string
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	LatencyMS        int32
	StatusCode       int32
	ErrorMessage     string
	RequestPath      string
	CreatedAt        time.Time
}

// UsageDetailRow is the single-row read model returned by GetUsageByID.
// It mirrors UsageRow but also includes RequestBody / ResponseBody.
type UsageDetailRow struct {
	ID               int64
	SessionID        *int64
	ProviderID       int64
	ProviderName     string
	Model            string
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	LatencyMS        int32
	StatusCode       int32
	ErrorMessage     string
	RequestPath      string
	RequestBody      string
	ResponseBody     string
	CreatedAt        time.Time
}

// GetUsageByID returns a single usage row including the large body
// columns. Returns pgx.ErrNoRows when the id doesn't exist.
func (r *PostgresRepo) GetUsageByID(ctx context.Context, id int64) (*UsageDetailRow, error) {
	row, err := r.q.GetUsageByID(ctx, id)
	if err != nil {
		return nil, err
	}
	ur := &UsageDetailRow{
		ID:               row.ID,
		ProviderID:       row.ProviderID,
		ProviderName:     row.ProviderName,
		Model:            row.Model,
		PromptTokens:     row.PromptTokens,
		CompletionTokens: row.CompletionTokens,
		TotalTokens:      row.TotalTokens,
		LatencyMS:        row.LatencyMs,
		StatusCode:       row.StatusCode,
		ErrorMessage:     row.ErrorMessage,
		RequestPath:      row.RequestPath,
		RequestBody:      row.RequestBody,
		ResponseBody:     row.ResponseBody,
		CreatedAt:        row.CreatedAt.Time,
	}
	if row.SessionID.Valid {
		v := row.SessionID.Int64
		ur.SessionID = &v
	}
	return ur, nil
}

// ---- export ----

const exportUsagePageSize = 500

// ExportUsageCSV pages through the usage log in small batches and writes
// them as CSV to w. Only summary columns are included (no request_body /
// response_body).
func (r *PostgresRepo) ExportUsageCSV(ctx context.Context, w io.Writer, providerID *int64, since *time.Time) error {
	provArg, sinceArg := usageFilterArgs(providerID, since)

	// BOM-free; the ZIP content-type declares UTF-8.
	if _, err := io.WriteString(w, "created_at,provider_name,model,prompt_tokens,completion_tokens,total_tokens,latency_ms,status_code,session_id\n"); err != nil {
		return err
	}

	for offset := 0; ; offset += exportUsagePageSize {
		rows, err := r.q.ExportUsageCSV(ctx, llmproviderdb.ExportUsageCSVParams{
			ProviderID: provArg,
			Since:      sinceArg,
			Lim:        exportUsagePageSize,
			Off:        int32(offset),
		})
		if err != nil {
			return fmt.Errorf("export csv query: %w", err)
		}
		if len(rows) == 0 {
			return nil
		}

		for _, row := range rows {
			var sid string
			if row.SessionID.Valid {
				sid = fmt.Sprintf("%d", row.SessionID.Int64)
			}
			line := fmt.Sprintf("%s,%s,%s,%d,%d,%d,%d,%d,%s\n",
				row.CreatedAt.Time.UTC().Format(time.RFC3339),
				csvEscape(row.ProviderName),
				csvEscape(row.Model),
				row.PromptTokens,
				row.CompletionTokens,
				row.TotalTokens,
				row.LatencyMs,
				row.StatusCode,
				sid,
			)
			if _, err := io.WriteString(w, line); err != nil {
				return err
			}
		}
		if len(rows) < exportUsagePageSize {
			return nil
		}
	}
}

// ExportUsageJSONL pages through the full usage log in small batches and
// writes them as JSONL (one JSON object per line) to w. All columns are
// included, including request_body and response_body.
func (r *PostgresRepo) ExportUsageJSONL(ctx context.Context, w io.Writer, providerID *int64, since *time.Time) error {
	provArg, sinceArg := usageFilterArgs(providerID, since)

	for offset := 0; ; offset += exportUsagePageSize {
		rows, err := r.q.ExportUsageJSONL(ctx, llmproviderdb.ExportUsageJSONLParams{
			ProviderID: provArg,
			Since:      sinceArg,
			Lim:        exportUsagePageSize,
			Off:        int32(offset),
		})
		if err != nil {
			return fmt.Errorf("export jsonl query: %w", err)
		}
		if len(rows) == 0 {
			return nil
		}

		for _, row := range rows {
			obj := exportJSONLRow{
				CreatedAt:        row.CreatedAt.Time.UTC().Format(time.RFC3339),
				ProviderName:     row.ProviderName,
				Model:            row.Model,
				PromptTokens:     row.PromptTokens,
				CompletionTokens: row.CompletionTokens,
				TotalTokens:      row.TotalTokens,
				LatencyMS:        row.LatencyMs,
				StatusCode:       row.StatusCode,
				RequestPath:      row.RequestPath,
				ErrorMessage:     row.ErrorMessage,
				RequestBody:      row.RequestBody,
				ResponseBody:     row.ResponseBody,
			}
			if row.SessionID.Valid {
				v := row.SessionID.Int64
				obj.SessionID = &v
			}

			b, err := json.Marshal(obj)
			if err != nil {
				return fmt.Errorf("export jsonl marshal: %w", err)
			}
			if _, err := w.Write(append(b, '\n')); err != nil {
				return err
			}
		}
		if len(rows) < exportUsagePageSize {
			return nil
		}
	}
}

type exportJSONLRow struct {
	CreatedAt        string `json:"created_at"`
	ProviderName     string `json:"provider_name"`
	Model            string `json:"model"`
	PromptTokens     int32  `json:"prompt_tokens"`
	CompletionTokens int32  `json:"completion_tokens"`
	TotalTokens      int32  `json:"total_tokens"`
	LatencyMS        int32  `json:"latency_ms"`
	StatusCode       int32  `json:"status_code"`
	ErrorMessage     string `json:"error_message"`
	RequestPath      string `json:"request_path"`
	RequestBody      string `json:"request_body"`
	ResponseBody     string `json:"response_body"`
	SessionID        *int64 `json:"session_id,omitempty"`
}

// csvEscape escapes a string for CSV: wraps in double-quotes and doubles any
// embedded double-quotes when the value contains a comma, quote, or newline.
func csvEscape(s string) string {
	for i := 0; i < len(s); i++ {
		if s[i] == ',' || s[i] == '"' || s[i] == '\n' || s[i] == '\r' {
			quoted := make([]byte, 0, len(s)+4)
			quoted = append(quoted, '"')
			for j := 0; j < len(s); j++ {
				if s[j] == '"' {
					quoted = append(quoted, '"', '"')
				} else {
					quoted = append(quoted, s[j])
				}
			}
			quoted = append(quoted, '"')
			return string(quoted)
		}
	}
	return s
}

// ---- cleanup ----

// DeleteUsageBefore hard-deletes usage-log rows whose created_at is strictly
// before cutoff and returns how many rows were removed. Called only by the
// background reaper (service/reaper.go); not part of the domain.Repo interface
// because admin handlers should never trigger mass deletion.
func (r *PostgresRepo) DeleteUsageBefore(ctx context.Context, cutoff time.Time) (int64, error) {
	return r.q.DeleteUsageBefore(ctx, pgtype.Timestamptz{Time: cutoff, Valid: true})
}

// ---- row → domain ----

func providerFromRow(r llmproviderdb.LlmProvider) *domain.Provider {
	return &domain.Provider{
		ID:            r.ID,
		Name:          r.Name,
		Type:          domain.ProviderType(r.Type),
		BaseURL:       r.BaseUrl,
		ApiKey:        r.ApiKeyEncrypted,
		AllowedModels: r.AllowedModels,
		Disabled:      r.Disabled,
		ActorID:       r.ActorID,
		CreatedAt:     r.CreatedAt.Time,
		UpdatedAt:     r.UpdatedAt.Time,
	}
}

// ---- model groups ----

// CreateGroup inserts a new model group row.
func (r *PostgresRepo) CreateGroup(ctx context.Context, g *domain.ModelGroup) (*domain.ModelGroup, error) {
	row, err := r.q.CreateGroup(ctx, llmproviderdb.CreateGroupParams{
		Name:        g.Name,
		Description: g.Description,
		ActorID:     g.ActorID,
	})
	if err != nil {
		if database.IsUniqueViolation(err) {
			return nil, domain.ErrGroupNameConflict
		}
		return nil, err
	}
	return groupFromRow(row), nil
}

// GetGroupByName looks up a group by its unique name.
func (r *PostgresRepo) GetGroupByName(ctx context.Context, name string) (*domain.ModelGroup, error) {
	row, err := r.q.GetGroupByName(ctx, name)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrGroupNotFound
		}
		return nil, err
	}
	return groupFromRow(row), nil
}

// GetGroupByID looks up a group by its primary key.
func (r *PostgresRepo) GetGroupByID(ctx context.Context, id int64) (*domain.ModelGroup, error) {
	row, err := r.q.GetGroupByID(ctx, id)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrGroupNotFound
		}
		return nil, err
	}
	return groupFromRow(row), nil
}

// ListGroups returns all groups ordered by name.
func (r *PostgresRepo) ListGroups(ctx context.Context) ([]*domain.ModelGroup, error) {
	rows, err := r.q.ListGroups(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*domain.ModelGroup, 0, len(rows))
	for _, row := range rows {
		out = append(out, groupFromRow(row))
	}
	return out, nil
}

// UpdateGroup updates the description of an existing group.
func (r *PostgresRepo) UpdateGroup(ctx context.Context, g *domain.ModelGroup) (*domain.ModelGroup, error) {
	row, err := r.q.UpdateGroup(ctx, llmproviderdb.UpdateGroupParams{
		ID:          g.ID,
		Description: g.Description,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrGroupNotFound
		}
		return nil, err
	}
	return groupFromRow(row), nil
}

// DeleteGroup deletes a group (and CASCADE deletes its members).
func (r *PostgresRepo) DeleteGroup(ctx context.Context, id int64) error {
	n, err := r.q.DeleteGroup(ctx, id)
	if err != nil {
		return err
	}
	if n == 0 {
		return domain.ErrGroupNotFound
	}
	return nil
}

// CountGroupsByName returns the number of groups with the given name (0 or 1).
func (r *PostgresRepo) CountGroupsByName(ctx context.Context, name string) (int64, error) {
	return r.q.CountGroupsByName(ctx, name)
}

// ---- model group members ----

// ReplaceMembers deletes all existing members for a group and inserts the new
// list. The caller must provide members with priority already set in order.
// This runs in a single transaction for atomicity.
func (r *PostgresRepo) ReplaceMembers(ctx context.Context, groupID int64, members []*domain.GroupMember) error {
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx)

	q := llmproviderdb.New(tx)

	if err := q.ReplaceMembers(ctx, groupID); err != nil {
		return err
	}

	for _, m := range members {
		if err := q.InsertMember(ctx, llmproviderdb.InsertMemberParams{
			GroupID:    groupID,
			ProviderID: m.ProviderID,
			Model:      m.Model,
			Priority:   m.Priority,
		}); err != nil {
			return err
		}
	}

	return tx.Commit(ctx)
}

// ListMembersByGroupID returns all members of a group joined with provider info,
// ordered by priority ASC.
func (r *PostgresRepo) ListMembersByGroupID(ctx context.Context, groupID int64) ([]*domain.GroupMember, error) {
	rows, err := r.q.ListMembersByGroupID(ctx, groupID)
	if err != nil {
		return nil, err
	}
	out := make([]*domain.GroupMember, 0, len(rows))
	for _, row := range rows {
		out = append(out, memberFromListRow(row))
	}
	return out, nil
}

// GetMemberByID returns a single member by its primary key.
func (r *PostgresRepo) GetMemberByID(ctx context.Context, id int64) (*domain.GroupMember, error) {
	row, err := r.q.GetMemberByID(ctx, id)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrGroupMemberNotFound
		}
		return nil, err
	}
	return memberFromGetRow(row), nil
}

// UpdateMemberHealth applies a HealthPatch to a single member row.
// Each field in the patch is only applied when non-nil (or for
// auto_disabled_until, when the null-flag is set).
func (r *PostgresRepo) UpdateMemberHealth(ctx context.Context, id int64, patch domain.HealthPatch) error {
	params := llmproviderdb.UpdateMemberHealthParams{ID: id}

	if patch.ManualDisabled != nil {
		params.ManualDisabled = pgtype.Bool{Bool: *patch.ManualDisabled, Valid: true}
	}
	if patch.AutoDisabledUntil != nil {
		params.AutoDisabledUntil = pgtype.Timestamptz{Time: *patch.AutoDisabledUntil, Valid: true}
	} else if patch.AutoDisabledUntil == nil && patch.BackoffStep != nil {
		// When AutoDisabledUntil is nil in the patch AND BackoffStep is being set,
		// we interpret this as "clear the auto-disabled state" (e.g. on success or manual enable).
		// The caller explicitly passes nil for AutoDisabledUntil to signal clearing.
		params.AutoDisabledUntilNull = pgtype.Bool{Bool: true, Valid: true}
	}
	if patch.BackoffStep != nil {
		params.BackoffStep = pgtype.Int4{Int32: *patch.BackoffStep, Valid: true}
	}
	if patch.LastFailureAt != nil {
		params.LastFailureAt = pgtype.Timestamptz{Time: *patch.LastFailureAt, Valid: true}
	}
	if patch.LastFailureMsg != nil {
		params.LastFailureMsg = pgtype.Text{String: *patch.LastFailureMsg, Valid: true}
	}
	if patch.LastSuccessAt != nil {
		params.LastSuccessAt = pgtype.Timestamptz{Time: *patch.LastSuccessAt, Valid: true}
	}
	if patch.LastCheckedAt != nil {
		params.LastCheckedAt = pgtype.Timestamptz{Time: *patch.LastCheckedAt, Valid: true}
	}

	n, err := r.q.UpdateMemberHealth(ctx, params)
	if err != nil {
		return err
	}
	if n == 0 {
		return domain.ErrGroupMemberNotFound
	}
	return nil
}

// ---- row → domain (groups) ----

func groupFromRow(r llmproviderdb.LlmModelGroup) *domain.ModelGroup {
	return &domain.ModelGroup{
		ID:          r.ID,
		Name:        r.Name,
		Description: r.Description,
		ActorID:     r.ActorID,
		CreatedAt:   r.CreatedAt.Time,
		UpdatedAt:   r.UpdatedAt.Time,
	}
}

func memberFromListRow(r llmproviderdb.ListMembersByGroupIDRow) *domain.GroupMember {
	m := &domain.GroupMember{
		ID:               r.ID,
		GroupID:          r.GroupID,
		ProviderID:       r.ProviderID,
		ProviderName:     r.ProviderName,
		Model:            r.Model,
		Priority:         r.Priority,
		ManualDisabled:   r.ManualDisabled,
		BackoffStep:      r.BackoffStep,
		LastFailureMsg:   r.LastFailureMsg,
		ProviderDisabled: r.ProviderDisabled,
	}
	if r.AutoDisabledUntil.Valid {
		m.AutoDisabledUntil = &r.AutoDisabledUntil.Time
	}
	if r.LastFailureAt.Valid {
		m.LastFailureAt = &r.LastFailureAt.Time
	}
	if r.LastSuccessAt.Valid {
		m.LastSuccessAt = &r.LastSuccessAt.Time
	}
	if r.LastCheckedAt.Valid {
		m.LastCheckedAt = &r.LastCheckedAt.Time
	}
	return m
}

func memberFromGetRow(r llmproviderdb.GetMemberByIDRow) *domain.GroupMember {
	m := &domain.GroupMember{
		ID:               r.ID,
		GroupID:          r.GroupID,
		ProviderID:       r.ProviderID,
		ProviderName:     r.ProviderName,
		Model:            r.Model,
		Priority:         r.Priority,
		ManualDisabled:   r.ManualDisabled,
		BackoffStep:      r.BackoffStep,
		LastFailureMsg:   r.LastFailureMsg,
		ProviderDisabled: r.ProviderDisabled,
	}
	if r.AutoDisabledUntil.Valid {
		m.AutoDisabledUntil = &r.AutoDisabledUntil.Time
	}
	if r.LastFailureAt.Valid {
		m.LastFailureAt = &r.LastFailureAt.Time
	}
	if r.LastSuccessAt.Valid {
		m.LastSuccessAt = &r.LastSuccessAt.Time
	}
	if r.LastCheckedAt.Valid {
		m.LastCheckedAt = &r.LastCheckedAt.Time
	}
	return m
}



// ---- llm models ----

// CreateModel inserts a new llm_models row. Returns ErrModelNameConflict on
// unique violation (name already taken, including cross-group conflict).
func (r *PostgresRepo) CreateModel(ctx context.Context, m *domain.ModelDefinition) (*domain.ModelDefinition, error) {
	effortJSON, err := json.Marshal(m.ReasoningEffortMap)
	if err != nil {
		return nil, fmt.Errorf("marshal reasoning_effort_map: %w", err)
	}
	row, err := r.q.CreateModel(ctx, llmproviderdb.CreateModelParams{
		Name:               m.Name,
		DisplayName:        m.DisplayName,
		ContextWindow:      m.ContextWindow,
		MaxOutputTokens:    m.MaxOutputTokens,
		Vision:             m.Vision,
		Reasoning:          m.Reasoning,
		ReasoningEffortMap: effortJSON,
		GroupID:            m.GroupID,
		ActorID:            m.ActorID,
	})
	if err != nil {
		if database.IsUniqueViolation(err) {
			return nil, domain.ErrModelNameConflict
		}
		return nil, err
	}
	return modelFromRow(row), nil
}

// GetModelByName looks up a model by its unique name.
func (r *PostgresRepo) GetModelByName(ctx context.Context, name string) (*domain.ModelDefinition, error) {
	row, err := r.q.GetModelByName(ctx, name)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrModelNotFound
		}
		return nil, err
	}
	return modelFromRow(row), nil
}

// GetModelByID looks up a model by its primary key.
func (r *PostgresRepo) GetModelByID(ctx context.Context, id int64) (*domain.ModelDefinition, error) {
	row, err := r.q.GetModelByID(ctx, id)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrModelNotFound
		}
		return nil, err
	}
	return modelFromRow(row), nil
}

// ListModels returns all models ordered by name.
func (r *PostgresRepo) ListModels(ctx context.Context) ([]*domain.ModelDefinition, error) {
	rows, err := r.q.ListModels(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*domain.ModelDefinition, 0, len(rows))
	for _, row := range rows {
		out = append(out, modelFromRow(row))
	}
	return out, nil
}

// UpdateModel updates the mutable fields of a model definition.
func (r *PostgresRepo) UpdateModel(ctx context.Context, m *domain.ModelDefinition) (*domain.ModelDefinition, error) {
	effortJSON, err := json.Marshal(m.ReasoningEffortMap)
	if err != nil {
		return nil, fmt.Errorf("marshal reasoning_effort_map: %w", err)
	}
	row, err := r.q.UpdateModel(ctx, llmproviderdb.UpdateModelParams{
		ID:                 m.ID,
		DisplayName:        m.DisplayName,
		ContextWindow:      m.ContextWindow,
		MaxOutputTokens:    m.MaxOutputTokens,
		Vision:             m.Vision,
		Reasoning:          m.Reasoning,
		ReasoningEffortMap: effortJSON,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrModelNotFound
		}
		return nil, err
	}
	return modelFromRow(row), nil
}

// DeleteModel deletes a model definition by id.
func (r *PostgresRepo) DeleteModel(ctx context.Context, id int64) error {
	n, err := r.q.DeleteModel(ctx, id)
	if err != nil {
		return err
	}
	if n == 0 {
		return domain.ErrModelNotFound
	}
	return nil
}

// CountModelsByName returns the number of models with the given name (0 or 1).
func (r *PostgresRepo) CountModelsByName(ctx context.Context, name string) (int64, error) {
	return r.q.CountModelsByName(ctx, name)
}

// ---- row → domain (models) ----

func modelFromRow(r llmproviderdb.LlmModel) *domain.ModelDefinition {
	m := &domain.ModelDefinition{
		ID:                 r.ID,
		Name:               r.Name,
		DisplayName:        r.DisplayName,
		ContextWindow:      r.ContextWindow,
		MaxOutputTokens:    r.MaxOutputTokens,
		Vision:             r.Vision,
		Reasoning:          r.Reasoning,
		ReasoningEffortMap: make(map[string]string),
		GroupID:            r.GroupID,
		ActorID:            r.ActorID,
		CreatedAt:          r.CreatedAt.Time,
		UpdatedAt:          r.UpdatedAt.Time,
	}
	if len(r.ReasoningEffortMap) > 0 {
		if err := json.Unmarshal(r.ReasoningEffortMap, &m.ReasoningEffortMap); err != nil {
			// Should never happen — the DB stores valid JSON.
			m.ReasoningEffortMap = make(map[string]string)
		}
	}
	return m
}

// ---- atomic model+group creation ----

// CreateModelAtomic creates a model, its backing group, and members in a
// single transaction. Returns the created model (with populated ID).
func (r *PostgresRepo) CreateModelAtomic(
	ctx context.Context,
	model *domain.ModelDefinition,
	members []*domain.GroupMember,
) (*domain.ModelDefinition, error) {
	if model.ReasoningEffortMap == nil {
		model.ReasoningEffortMap = make(map[string]string)
	}

	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback(ctx)

	q := llmproviderdb.New(tx)

	// 1. Create the group
	groupRow, err := q.CreateGroup(ctx, llmproviderdb.CreateGroupParams{
		Name:        model.Name,
		Description: "auto-managed by model definition",
		ActorID:     model.ActorID,
	})
	if err != nil {
		if database.IsUniqueViolation(err) {
			return nil, domain.ErrGroupNameConflict
		}
		return nil, fmt.Errorf("create group: %w", err)
	}
	model.GroupID = groupRow.ID

	// 2. Create the model
	effortJSON, err := json.Marshal(model.ReasoningEffortMap)
	if err != nil {
		return nil, fmt.Errorf("marshal reasoning_effort_map: %w", err)
	}
	modelRow, err := q.CreateModel(ctx, llmproviderdb.CreateModelParams{
		Name:               model.Name,
		DisplayName:        model.DisplayName,
		ContextWindow:      model.ContextWindow,
		MaxOutputTokens:    model.MaxOutputTokens,
		Vision:             model.Vision,
		Reasoning:          model.Reasoning,
		ReasoningEffortMap: effortJSON,
		GroupID:            model.GroupID,
		ActorID:            model.ActorID,
	})
	if err != nil {
		if database.IsUniqueViolation(err) {
			return nil, domain.ErrModelNameConflict
		}
		return nil, fmt.Errorf("create model: %w", err)
	}

	// 3. Write members (if any)
	if len(members) > 0 {
		// Delete any existing members first (should be none, but defensive)
		if err := q.ReplaceMembers(ctx, model.GroupID); err != nil {
			return nil, err
		}
		for i, m := range members {
			m.GroupID = model.GroupID
			m.Priority = int32(i)
			if err := q.InsertMember(ctx, llmproviderdb.InsertMemberParams{
				GroupID:    m.GroupID,
				ProviderID: m.ProviderID,
				Model:      m.Model,
				Priority:   m.Priority,
			}); err != nil {
				return nil, err
			}
		}
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}

	return modelFromRow(modelRow), nil
}

// DeleteModelAtomic deletes a model and its backing group in a single
// transaction. The model row must be deleted first (FK from llm_models
// to llm_model_groups with ON DELETE RESTRICT), then the group (CASCADE
// will clean up members).
func (r *PostgresRepo) DeleteModelAtomic(ctx context.Context, modelID int64) error {
	m, err := r.GetModelByID(ctx, modelID)
	if err != nil {
		return err
	}

	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx)

	q := llmproviderdb.New(tx)

	// 1. Delete the model first (FK: llm_models.group_id → llm_model_groups.id ON DELETE RESTRICT)
	n, err := q.DeleteModel(ctx, modelID)
	if err != nil {
		return err
	}
	if n == 0 {
		return domain.ErrModelNotFound
	}

	// 2. Delete the group (CASCADE cleans up members). Safe because
	// step 1 already removed the model row that held the RESTRICT FK.
	gn, gErr := q.DeleteGroup(ctx, m.GroupID)
	if gErr != nil {
		return gErr
	}
	if gn == 0 {
		return domain.ErrGroupNotFound
	}

	return tx.Commit(ctx)
}

// UpdateModelWithMembersAtomic updates a model's fields and optionally
// replaces its group members in a single transaction. members==nil means
// "leave members unchanged".
func (r *PostgresRepo) UpdateModelWithMembersAtomic(
	ctx context.Context,
	model *domain.ModelDefinition,
	members []*domain.GroupMember,
) (*domain.ModelDefinition, error) {
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback(ctx)

	q := llmproviderdb.New(tx)

	effortJSON, err := json.Marshal(model.ReasoningEffortMap)
	if err != nil {
		return nil, fmt.Errorf("marshal reasoning_effort_map: %w", err)
	}
	row, err := q.UpdateModel(ctx, llmproviderdb.UpdateModelParams{
		ID:                 model.ID,
		DisplayName:        model.DisplayName,
		ContextWindow:      model.ContextWindow,
		MaxOutputTokens:    model.MaxOutputTokens,
		Vision:             model.Vision,
		Reasoning:          model.Reasoning,
		ReasoningEffortMap: effortJSON,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, domain.ErrModelNotFound
		}
		return nil, err
	}

	if members != nil {
		if err := q.ReplaceMembers(ctx, model.GroupID); err != nil {
			return nil, err
		}
		for i, m := range members {
			m.GroupID = model.GroupID
			m.Priority = int32(i)
			if err := q.InsertMember(ctx, llmproviderdb.InsertMemberParams{
				GroupID:    m.GroupID,
				ProviderID: m.ProviderID,
				Model:      m.Model,
				Priority:   m.Priority,
			}); err != nil {
				return nil, err
			}
		}
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}

	return modelFromRow(row), nil
}

// ---- pgx error helpers ----
