// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package workflowdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendWorkflowJobLog = `-- name: AppendWorkflowJobLog :exec

INSERT INTO workflow_job_logs (workflow_job_run_id, stream, line, step_id)
VALUES ($1, $2, $3, $4)
`

type AppendWorkflowJobLogParams struct {
	WorkflowJobRunID int64
	Stream           string
	Line             string
	StepID           pgtype.Text
}

// ---- workflow_job_logs ----
func (q *Queries) AppendWorkflowJobLog(ctx context.Context, arg AppendWorkflowJobLogParams) error {
	_, err := q.db.Exec(ctx, appendWorkflowJobLog,
		arg.WorkflowJobRunID,
		arg.Stream,
		arg.Line,
		arg.StepID,
	)
	return err
}

const cancelRunningWorkflowJobs = `-- name: CancelRunningWorkflowJobs :exec
UPDATE workflow_job_runs
SET status = 'cancelled', finished_at = NOW()
WHERE workflow_run_id = $1
  AND status = 'running'
`

func (q *Queries) CancelRunningWorkflowJobs(ctx context.Context, workflowRunID int64) error {
	_, err := q.db.Exec(ctx, cancelRunningWorkflowJobs, workflowRunID)
	return err
}

const claimNextWorkflowJob = `-- name: ClaimNextWorkflowJob :one
UPDATE workflow_job_runs
SET status = 'running', runner_id = $1, started_at = NOW()
WHERE id = (
    SELECT j.id FROM workflow_job_runs j
    WHERE j.status = 'pending'
      AND NOT EXISTS (
        SELECT 1 FROM workflow_job_runs j2
        WHERE j2.workflow_run_id = j.workflow_run_id
          AND j2.sequence_index < j.sequence_index
          AND j2.status NOT IN ('success', 'skipped', 'failed', 'cancelled')
      )
    ORDER BY j.sequence_index ASC, j.created_at ASC, j.id ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, workflow_run_id, job_key, display_name, status, sequence_index, working_directory, timeout_minutes, runner_id, container_id, env_json, steps_json, started_at, finished_at, exit_code, error_message, created_at, step_outputs_json, job_outputs_json, job_outputs_raw_json
`

// Only claim a job if no earlier-sequence job in the same run is still
// pending or running. This preserves the sequential execution guarantee:
// jobs within a workflow run execute one at a time in sequence order.
// DEPRECATED: kept for backward-compat; new code uses ClaimNextWorkflowJobs.
func (q *Queries) ClaimNextWorkflowJob(ctx context.Context, runnerID pgtype.Int8) (WorkflowJobRun, error) {
	row := q.db.QueryRow(ctx, claimNextWorkflowJob, runnerID)
	var i WorkflowJobRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.JobKey,
		&i.DisplayName,
		&i.Status,
		&i.SequenceIndex,
		&i.WorkingDirectory,
		&i.TimeoutMinutes,
		&i.RunnerID,
		&i.ContainerID,
		&i.EnvJson,
		&i.StepsJson,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StepOutputsJson,
		&i.JobOutputsJson,
		&i.JobOutputsRawJson,
	)
	return i, err
}

const claimNextWorkflowJobs = `-- name: ClaimNextWorkflowJobs :many
UPDATE workflow_job_runs
SET status = 'running', runner_id = $1, started_at = NOW()
WHERE id = ANY(ARRAY(
    SELECT j.id FROM workflow_job_runs j
    WHERE j.status = 'pending'
      AND NOT EXISTS (
        SELECT 1 FROM workflow_job_runs j2
        WHERE j2.workflow_run_id = j.workflow_run_id
          AND j2.sequence_index < j.sequence_index
          AND j2.status NOT IN ('success', 'skipped', 'failed', 'cancelled')
      )
    ORDER BY j.sequence_index ASC, j.created_at ASC, j.id ASC
    LIMIT $2
    FOR UPDATE SKIP LOCKED
))
RETURNING id, workflow_run_id, job_key, display_name, status, sequence_index, working_directory, timeout_minutes, runner_id, container_id, env_json, steps_json, started_at, finished_at, exit_code, error_message, created_at, step_outputs_json, job_outputs_json, job_outputs_raw_json
`

type ClaimNextWorkflowJobsParams struct {
	RunnerID pgtype.Int8
	Limit    int32
}

// Claims up to sqlc.arg('limit') pending jobs for a runner, preserving
// the sequential-execution guarantee: jobs within the same workflow_run
// execute one at a time in sequence order. The NOT EXISTS subquery
// ensures no earlier-sequence job in the same run is still pending or
// running, so multi-job batches naturally span different workflow_runs.
// FOR UPDATE SKIP LOCKED keeps concurrent runners from colliding.
func (q *Queries) ClaimNextWorkflowJobs(ctx context.Context, arg ClaimNextWorkflowJobsParams) ([]WorkflowJobRun, error) {
	rows, err := q.db.Query(ctx, claimNextWorkflowJobs, arg.RunnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowJobRun{}
	for rows.Next() {
		var i WorkflowJobRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowRunID,
			&i.JobKey,
			&i.DisplayName,
			&i.Status,
			&i.SequenceIndex,
			&i.WorkingDirectory,
			&i.TimeoutMinutes,
			&i.RunnerID,
			&i.ContainerID,
			&i.EnvJson,
			&i.StepsJson,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ExitCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StepOutputsJson,
			&i.JobOutputsJson,
			&i.JobOutputsRawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWorkflowJobPhase = `-- name: CreateWorkflowJobPhase :one

INSERT INTO workflow_job_phases (
    workflow_job_run_id, phase, status, sequence_index, image_ref
) VALUES (
    $1, $2,
    'pending', $3, $4
)
ON CONFLICT (workflow_job_run_id, phase) DO NOTHING
RETURNING id, workflow_job_run_id, phase, status, sequence_index, started_at, finished_at, exit_code, error_message, image_ref, created_at
`

type CreateWorkflowJobPhaseParams struct {
	WorkflowJobRunID int64
	Phase            string
	SequenceIndex    int32
	ImageRef         string
}

// ---- workflow_job_phases ----
// Insert a phase row; ON CONFLICT DO NOTHING makes it idempotent.
// Returns the row (either newly inserted or existing).
func (q *Queries) CreateWorkflowJobPhase(ctx context.Context, arg CreateWorkflowJobPhaseParams) (WorkflowJobPhase, error) {
	row := q.db.QueryRow(ctx, createWorkflowJobPhase,
		arg.WorkflowJobRunID,
		arg.Phase,
		arg.SequenceIndex,
		arg.ImageRef,
	)
	var i WorkflowJobPhase
	err := row.Scan(
		&i.ID,
		&i.WorkflowJobRunID,
		&i.Phase,
		&i.Status,
		&i.SequenceIndex,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.ImageRef,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkflowJobRun = `-- name: CreateWorkflowJobRun :one

INSERT INTO workflow_job_runs (
    workflow_run_id, job_key, display_name, status, sequence_index,
    working_directory, timeout_minutes, env_json, steps_json,
    job_outputs_raw_json
) VALUES (
    $1, $2, $3,
    'pending', $4,
    $5, $6,
    $7, $8,
    $9
) RETURNING id, workflow_run_id, job_key, display_name, status, sequence_index, working_directory, timeout_minutes, runner_id, container_id, env_json, steps_json, started_at, finished_at, exit_code, error_message, created_at, step_outputs_json, job_outputs_json, job_outputs_raw_json
`

type CreateWorkflowJobRunParams struct {
	WorkflowRunID     int64
	JobKey            string
	DisplayName       string
	SequenceIndex     int32
	WorkingDirectory  string
	TimeoutMinutes    int32
	EnvJson           []byte
	StepsJson         []byte
	JobOutputsRawJson []byte
}

// ---- workflow_job_runs ----
func (q *Queries) CreateWorkflowJobRun(ctx context.Context, arg CreateWorkflowJobRunParams) (WorkflowJobRun, error) {
	row := q.db.QueryRow(ctx, createWorkflowJobRun,
		arg.WorkflowRunID,
		arg.JobKey,
		arg.DisplayName,
		arg.SequenceIndex,
		arg.WorkingDirectory,
		arg.TimeoutMinutes,
		arg.EnvJson,
		arg.StepsJson,
		arg.JobOutputsRawJson,
	)
	var i WorkflowJobRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.JobKey,
		&i.DisplayName,
		&i.Status,
		&i.SequenceIndex,
		&i.WorkingDirectory,
		&i.TimeoutMinutes,
		&i.RunnerID,
		&i.ContainerID,
		&i.EnvJson,
		&i.StepsJson,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StepOutputsJson,
		&i.JobOutputsJson,
		&i.JobOutputsRawJson,
	)
	return i, err
}

const createWorkflowRun = `-- name: CreateWorkflowRun :one


INSERT INTO workflow_runs (
    repo_id, workflow_name, source_file, status, event_name,
    cause_id, ref, commit_sha, container_snapshot_json, trigger_payload_json,
    workflow_token,
    trigger_actor_kind, trigger_actor_user_id, trigger_actor_role_key,
    trigger_actor_workflow_run_id, trigger_actor_display_name,
    run_actor_kind, run_actor_user_id, run_actor_role_key,
    run_actor_workflow_run_id, run_actor_display_name
) VALUES (
    $1, $2, $3,
    'pending', $4,
    $5, $6, $7,
    $8, $9,
    $10,
    $11, $12, $13,
    $14, $15,
    $16, $17, $18,
    $19, $20
) RETURNING id, repo_id, workflow_name, source_file, status, event_name, cause_id, ref, commit_sha, container_snapshot_json, trigger_payload_json, started_at, finished_at, created_at, workflow_token, trigger_actor_kind, trigger_actor_user_id, trigger_actor_role_key, trigger_actor_workflow_run_id, trigger_actor_display_name, run_actor_kind, run_actor_user_id, run_actor_role_key, run_actor_workflow_run_id, run_actor_display_name
`

type CreateWorkflowRunParams struct {
	RepoID                    int64
	WorkflowName              string
	SourceFile                string
	EventName                 string
	CauseID                   pgtype.Int8
	Ref                       string
	CommitSha                 string
	ContainerSnapshotJson     []byte
	TriggerPayloadJson        []byte
	WorkflowToken             string
	TriggerActorKind          string
	TriggerActorUserID        pgtype.Int8
	TriggerActorRoleKey       string
	TriggerActorWorkflowRunID pgtype.Int8
	TriggerActorDisplayName   string
	RunActorKind              string
	RunActorUserID            pgtype.Int8
	RunActorRoleKey           string
	RunActorWorkflowRunID     pgtype.Int8
	RunActorDisplayName       string
}

// Workflow module queries.
// Naming convention: sqlc.arg('name') for named parameters.
// ---- workflow_runs ----
func (q *Queries) CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, createWorkflowRun,
		arg.RepoID,
		arg.WorkflowName,
		arg.SourceFile,
		arg.EventName,
		arg.CauseID,
		arg.Ref,
		arg.CommitSha,
		arg.ContainerSnapshotJson,
		arg.TriggerPayloadJson,
		arg.WorkflowToken,
		arg.TriggerActorKind,
		arg.TriggerActorUserID,
		arg.TriggerActorRoleKey,
		arg.TriggerActorWorkflowRunID,
		arg.TriggerActorDisplayName,
		arg.RunActorKind,
		arg.RunActorUserID,
		arg.RunActorRoleKey,
		arg.RunActorWorkflowRunID,
		arg.RunActorDisplayName,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.WorkflowName,
		&i.SourceFile,
		&i.Status,
		&i.EventName,
		&i.CauseID,
		&i.Ref,
		&i.CommitSha,
		&i.ContainerSnapshotJson,
		&i.TriggerPayloadJson,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.WorkflowToken,
		&i.TriggerActorKind,
		&i.TriggerActorUserID,
		&i.TriggerActorRoleKey,
		&i.TriggerActorWorkflowRunID,
		&i.TriggerActorDisplayName,
		&i.RunActorKind,
		&i.RunActorUserID,
		&i.RunActorRoleKey,
		&i.RunActorWorkflowRunID,
		&i.RunActorDisplayName,
	)
	return i, err
}

const getWorkflowJobPhase = `-- name: GetWorkflowJobPhase :one
SELECT id, workflow_job_run_id, phase, status, sequence_index, started_at, finished_at, exit_code, error_message, image_ref, created_at FROM workflow_job_phases
WHERE workflow_job_run_id = $1
  AND phase = $2
`

type GetWorkflowJobPhaseParams struct {
	WorkflowJobRunID int64
	Phase            string
}

func (q *Queries) GetWorkflowJobPhase(ctx context.Context, arg GetWorkflowJobPhaseParams) (WorkflowJobPhase, error) {
	row := q.db.QueryRow(ctx, getWorkflowJobPhase, arg.WorkflowJobRunID, arg.Phase)
	var i WorkflowJobPhase
	err := row.Scan(
		&i.ID,
		&i.WorkflowJobRunID,
		&i.Phase,
		&i.Status,
		&i.SequenceIndex,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.ImageRef,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkflowJobRun = `-- name: GetWorkflowJobRun :one
SELECT id, workflow_run_id, job_key, display_name, status, sequence_index, working_directory, timeout_minutes, runner_id, container_id, env_json, steps_json, started_at, finished_at, exit_code, error_message, created_at, step_outputs_json, job_outputs_json, job_outputs_raw_json FROM workflow_job_runs WHERE id = $1
`

func (q *Queries) GetWorkflowJobRun(ctx context.Context, id int64) (WorkflowJobRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowJobRun, id)
	var i WorkflowJobRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.JobKey,
		&i.DisplayName,
		&i.Status,
		&i.SequenceIndex,
		&i.WorkingDirectory,
		&i.TimeoutMinutes,
		&i.RunnerID,
		&i.ContainerID,
		&i.EnvJson,
		&i.StepsJson,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StepOutputsJson,
		&i.JobOutputsJson,
		&i.JobOutputsRawJson,
	)
	return i, err
}

const getWorkflowRun = `-- name: GetWorkflowRun :one
SELECT id, repo_id, workflow_name, source_file, status, event_name, cause_id, ref, commit_sha, container_snapshot_json, trigger_payload_json, started_at, finished_at, created_at, workflow_token, trigger_actor_kind, trigger_actor_user_id, trigger_actor_role_key, trigger_actor_workflow_run_id, trigger_actor_display_name, run_actor_kind, run_actor_user_id, run_actor_role_key, run_actor_workflow_run_id, run_actor_display_name FROM workflow_runs WHERE id = $1
`

func (q *Queries) GetWorkflowRun(ctx context.Context, id int64) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.WorkflowName,
		&i.SourceFile,
		&i.Status,
		&i.EventName,
		&i.CauseID,
		&i.Ref,
		&i.CommitSha,
		&i.ContainerSnapshotJson,
		&i.TriggerPayloadJson,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.WorkflowToken,
		&i.TriggerActorKind,
		&i.TriggerActorUserID,
		&i.TriggerActorRoleKey,
		&i.TriggerActorWorkflowRunID,
		&i.TriggerActorDisplayName,
		&i.RunActorKind,
		&i.RunActorUserID,
		&i.RunActorRoleKey,
		&i.RunActorWorkflowRunID,
		&i.RunActorDisplayName,
	)
	return i, err
}

const getWorkflowRunByToken = `-- name: GetWorkflowRunByToken :one
SELECT id, repo_id, workflow_name, status FROM workflow_runs
WHERE workflow_token = $1 AND workflow_token <> ''
`

type GetWorkflowRunByTokenRow struct {
	ID           int64
	RepoID       int64
	WorkflowName string
	Status       string
}

func (q *Queries) GetWorkflowRunByToken(ctx context.Context, token string) (GetWorkflowRunByTokenRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowRunByToken, token)
	var i GetWorkflowRunByTokenRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.WorkflowName,
		&i.Status,
	)
	return i, err
}

const listAgentWorkflowRunsByRepo = `-- name: ListAgentWorkflowRunsByRepo :many
SELECT id, repo_id, workflow_name, source_file, status, event_name, cause_id, ref, commit_sha, container_snapshot_json, trigger_payload_json, started_at, finished_at, created_at, workflow_token, trigger_actor_kind, trigger_actor_user_id, trigger_actor_role_key, trigger_actor_workflow_run_id, trigger_actor_display_name, run_actor_kind, run_actor_user_id, run_actor_role_key, run_actor_workflow_run_id, run_actor_display_name, COUNT(*) OVER() AS total_count
FROM workflow_runs
WHERE repo_id = $1
  AND workflow_name = '_agent'
  AND ($2 = '' OR status = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListAgentWorkflowRunsByRepoParams struct {
	RepoID int64
	Status interface{}
	Offset int32
	Limit  int32
}

type ListAgentWorkflowRunsByRepoRow struct {
	ID                        int64
	RepoID                    int64
	WorkflowName              string
	SourceFile                string
	Status                    string
	EventName                 string
	CauseID                   pgtype.Int8
	Ref                       string
	CommitSha                 string
	ContainerSnapshotJson     []byte
	TriggerPayloadJson        []byte
	StartedAt                 pgtype.Timestamptz
	FinishedAt                pgtype.Timestamptz
	CreatedAt                 pgtype.Timestamptz
	WorkflowToken             string
	TriggerActorKind          string
	TriggerActorUserID        pgtype.Int8
	TriggerActorRoleKey       string
	TriggerActorWorkflowRunID pgtype.Int8
	TriggerActorDisplayName   string
	RunActorKind              string
	RunActorUserID            pgtype.Int8
	RunActorRoleKey           string
	RunActorWorkflowRunID     pgtype.Int8
	RunActorDisplayName       string
	TotalCount                int64
}

// Internal list: only the hidden `_agent` workflow (agent-session spawner runs).
func (q *Queries) ListAgentWorkflowRunsByRepo(ctx context.Context, arg ListAgentWorkflowRunsByRepoParams) ([]ListAgentWorkflowRunsByRepoRow, error) {
	rows, err := q.db.Query(ctx, listAgentWorkflowRunsByRepo,
		arg.RepoID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentWorkflowRunsByRepoRow{}
	for rows.Next() {
		var i ListAgentWorkflowRunsByRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.WorkflowName,
			&i.SourceFile,
			&i.Status,
			&i.EventName,
			&i.CauseID,
			&i.Ref,
			&i.CommitSha,
			&i.ContainerSnapshotJson,
			&i.TriggerPayloadJson,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.WorkflowToken,
			&i.TriggerActorKind,
			&i.TriggerActorUserID,
			&i.TriggerActorRoleKey,
			&i.TriggerActorWorkflowRunID,
			&i.TriggerActorDisplayName,
			&i.RunActorKind,
			&i.RunActorUserID,
			&i.RunActorRoleKey,
			&i.RunActorWorkflowRunID,
			&i.RunActorDisplayName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowJobLogs = `-- name: ListWorkflowJobLogs :many
SELECT id, workflow_job_run_id, stream, line, created_at, step_id, COUNT(*) OVER() AS total_count
FROM workflow_job_logs
WHERE workflow_job_run_id = $1
  AND ($2::TEXT IS NULL OR step_id = $2)
  AND ($3::INT8 IS NULL OR id > $3)
ORDER BY created_at ASC, id ASC
LIMIT $5 OFFSET $4
`

type ListWorkflowJobLogsParams struct {
	WorkflowJobRunID int64
	StepID           pgtype.Text
	SinceID          pgtype.Int8
	Offset           int32
	Limit            int32
}

type ListWorkflowJobLogsRow struct {
	ID               int64
	WorkflowJobRunID int64
	Stream           string
	Line             string
	CreatedAt        pgtype.Timestamptz
	StepID           pgtype.Text
	TotalCount       int64
}

func (q *Queries) ListWorkflowJobLogs(ctx context.Context, arg ListWorkflowJobLogsParams) ([]ListWorkflowJobLogsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowJobLogs,
		arg.WorkflowJobRunID,
		arg.StepID,
		arg.SinceID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkflowJobLogsRow{}
	for rows.Next() {
		var i ListWorkflowJobLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowJobRunID,
			&i.Stream,
			&i.Line,
			&i.CreatedAt,
			&i.StepID,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowJobPhases = `-- name: ListWorkflowJobPhases :many
SELECT id, workflow_job_run_id, phase, status, sequence_index, started_at, finished_at, exit_code, error_message, image_ref, created_at FROM workflow_job_phases
WHERE workflow_job_run_id = $1
ORDER BY sequence_index ASC
`

func (q *Queries) ListWorkflowJobPhases(ctx context.Context, workflowJobRunID int64) ([]WorkflowJobPhase, error) {
	rows, err := q.db.Query(ctx, listWorkflowJobPhases, workflowJobRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowJobPhase{}
	for rows.Next() {
		var i WorkflowJobPhase
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowJobRunID,
			&i.Phase,
			&i.Status,
			&i.SequenceIndex,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ExitCode,
			&i.ErrorMessage,
			&i.ImageRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowJobRunsByRun = `-- name: ListWorkflowJobRunsByRun :many
SELECT id, workflow_run_id, job_key, display_name, status, sequence_index, working_directory, timeout_minutes, runner_id, container_id, env_json, steps_json, started_at, finished_at, exit_code, error_message, created_at, step_outputs_json, job_outputs_json, job_outputs_raw_json FROM workflow_job_runs
WHERE workflow_run_id = $1
ORDER BY sequence_index ASC
`

func (q *Queries) ListWorkflowJobRunsByRun(ctx context.Context, workflowRunID int64) ([]WorkflowJobRun, error) {
	rows, err := q.db.Query(ctx, listWorkflowJobRunsByRun, workflowRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowJobRun{}
	for rows.Next() {
		var i WorkflowJobRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowRunID,
			&i.JobKey,
			&i.DisplayName,
			&i.Status,
			&i.SequenceIndex,
			&i.WorkingDirectory,
			&i.TimeoutMinutes,
			&i.RunnerID,
			&i.ContainerID,
			&i.EnvJson,
			&i.StepsJson,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ExitCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StepOutputsJson,
			&i.JobOutputsJson,
			&i.JobOutputsRawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRunsByRepo = `-- name: ListWorkflowRunsByRepo :many
SELECT id, repo_id, workflow_name, source_file, status, event_name, cause_id, ref, commit_sha, container_snapshot_json, trigger_payload_json, started_at, finished_at, created_at, workflow_token, trigger_actor_kind, trigger_actor_user_id, trigger_actor_role_key, trigger_actor_workflow_run_id, trigger_actor_display_name, run_actor_kind, run_actor_user_id, run_actor_role_key, run_actor_workflow_run_id, run_actor_display_name, COUNT(*) OVER() AS total_count
FROM workflow_runs
WHERE repo_id = $1
  AND workflow_name <> '_agent'
  AND ($2 = '' OR workflow_name = $2)
  AND ($3 = '' OR status = $3)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListWorkflowRunsByRepoParams struct {
	RepoID       int64
	WorkflowName interface{}
	Status       interface{}
	Offset       int32
	Limit        int32
}

type ListWorkflowRunsByRepoRow struct {
	ID                        int64
	RepoID                    int64
	WorkflowName              string
	SourceFile                string
	Status                    string
	EventName                 string
	CauseID                   pgtype.Int8
	Ref                       string
	CommitSha                 string
	ContainerSnapshotJson     []byte
	TriggerPayloadJson        []byte
	StartedAt                 pgtype.Timestamptz
	FinishedAt                pgtype.Timestamptz
	CreatedAt                 pgtype.Timestamptz
	WorkflowToken             string
	TriggerActorKind          string
	TriggerActorUserID        pgtype.Int8
	TriggerActorRoleKey       string
	TriggerActorWorkflowRunID pgtype.Int8
	TriggerActorDisplayName   string
	RunActorKind              string
	RunActorUserID            pgtype.Int8
	RunActorRoleKey           string
	RunActorWorkflowRunID     pgtype.Int8
	RunActorDisplayName       string
	TotalCount                int64
}

// User-facing list: excludes the hidden `_agent` workflow (agent-session
// spawner runs). Callers that need internal rows use a dedicated query.
func (q *Queries) ListWorkflowRunsByRepo(ctx context.Context, arg ListWorkflowRunsByRepoParams) ([]ListWorkflowRunsByRepoRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowRunsByRepo,
		arg.RepoID,
		arg.WorkflowName,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkflowRunsByRepoRow{}
	for rows.Next() {
		var i ListWorkflowRunsByRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.WorkflowName,
			&i.SourceFile,
			&i.Status,
			&i.EventName,
			&i.CauseID,
			&i.Ref,
			&i.CommitSha,
			&i.ContainerSnapshotJson,
			&i.TriggerPayloadJson,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.WorkflowToken,
			&i.TriggerActorKind,
			&i.TriggerActorUserID,
			&i.TriggerActorRoleKey,
			&i.TriggerActorWorkflowRunID,
			&i.TriggerActorDisplayName,
			&i.RunActorKind,
			&i.RunActorUserID,
			&i.RunActorRoleKey,
			&i.RunActorWorkflowRunID,
			&i.RunActorDisplayName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRunsByRepoAndCommitSHA = `-- name: ListWorkflowRunsByRepoAndCommitSHA :many
SELECT id, repo_id, workflow_name, source_file, status, event_name, cause_id, ref, commit_sha, container_snapshot_json, trigger_payload_json, started_at, finished_at, created_at, workflow_token, trigger_actor_kind, trigger_actor_user_id, trigger_actor_role_key, trigger_actor_workflow_run_id, trigger_actor_display_name, run_actor_kind, run_actor_user_id, run_actor_role_key, run_actor_workflow_run_id, run_actor_display_name FROM workflow_runs
WHERE repo_id = $1 AND commit_sha = $2
  AND workflow_name <> '_agent'
ORDER BY created_at DESC
`

type ListWorkflowRunsByRepoAndCommitSHAParams struct {
	RepoID    int64
	CommitSha string
}

// User-facing CI status check: same internal filter as ListWorkflowRunsByRepo.
func (q *Queries) ListWorkflowRunsByRepoAndCommitSHA(ctx context.Context, arg ListWorkflowRunsByRepoAndCommitSHAParams) ([]WorkflowRun, error) {
	rows, err := q.db.Query(ctx, listWorkflowRunsByRepoAndCommitSHA, arg.RepoID, arg.CommitSha)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowRun{}
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.WorkflowName,
			&i.SourceFile,
			&i.Status,
			&i.EventName,
			&i.CauseID,
			&i.Ref,
			&i.CommitSha,
			&i.ContainerSnapshotJson,
			&i.TriggerPayloadJson,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.WorkflowToken,
			&i.TriggerActorKind,
			&i.TriggerActorUserID,
			&i.TriggerActorRoleKey,
			&i.TriggerActorWorkflowRunID,
			&i.TriggerActorDisplayName,
			&i.RunActorKind,
			&i.RunActorUserID,
			&i.RunActorRoleKey,
			&i.RunActorWorkflowRunID,
			&i.RunActorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkflowJobPhaseRunning = `-- name: MarkWorkflowJobPhaseRunning :exec
UPDATE workflow_job_phases
SET status = 'running', started_at = NOW()
WHERE workflow_job_run_id = $1
  AND phase = $2
  AND status = 'pending'
`

type MarkWorkflowJobPhaseRunningParams struct {
	WorkflowJobRunID int64
	Phase            string
}

func (q *Queries) MarkWorkflowJobPhaseRunning(ctx context.Context, arg MarkWorkflowJobPhaseRunningParams) error {
	_, err := q.db.Exec(ctx, markWorkflowJobPhaseRunning, arg.WorkflowJobRunID, arg.Phase)
	return err
}

const markWorkflowJobPhaseTerminal = `-- name: MarkWorkflowJobPhaseTerminal :exec
UPDATE workflow_job_phases
SET status = $1,
    exit_code = $2,
    error_message = $3,
    finished_at = NOW()
WHERE workflow_job_run_id = $4
  AND phase = $5
`

type MarkWorkflowJobPhaseTerminalParams struct {
	Status           string
	ExitCode         pgtype.Int4
	ErrorMessage     string
	WorkflowJobRunID int64
	Phase            string
}

func (q *Queries) MarkWorkflowJobPhaseTerminal(ctx context.Context, arg MarkWorkflowJobPhaseTerminalParams) error {
	_, err := q.db.Exec(ctx, markWorkflowJobPhaseTerminal,
		arg.Status,
		arg.ExitCode,
		arg.ErrorMessage,
		arg.WorkflowJobRunID,
		arg.Phase,
	)
	return err
}

const markWorkflowJobRunning = `-- name: MarkWorkflowJobRunning :exec
UPDATE workflow_job_runs
SET status = 'running', runner_id = $1, started_at = NOW()
WHERE id = $2
`

type MarkWorkflowJobRunningParams struct {
	RunnerID pgtype.Int8
	ID       int64
}

func (q *Queries) MarkWorkflowJobRunning(ctx context.Context, arg MarkWorkflowJobRunningParams) error {
	_, err := q.db.Exec(ctx, markWorkflowJobRunning, arg.RunnerID, arg.ID)
	return err
}

const markWorkflowJobTerminal = `-- name: MarkWorkflowJobTerminal :exec
UPDATE workflow_job_runs
SET status = $1,
    exit_code = $2,
    error_message = $3,
    finished_at = NOW()
WHERE id = $4
`

type MarkWorkflowJobTerminalParams struct {
	Status       string
	ExitCode     pgtype.Int4
	ErrorMessage string
	ID           int64
}

func (q *Queries) MarkWorkflowJobTerminal(ctx context.Context, arg MarkWorkflowJobTerminalParams) error {
	_, err := q.db.Exec(ctx, markWorkflowJobTerminal,
		arg.Status,
		arg.ExitCode,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const markWorkflowRunStarted = `-- name: MarkWorkflowRunStarted :exec
UPDATE workflow_runs
SET status = 'running', started_at = NOW()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) MarkWorkflowRunStarted(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markWorkflowRunStarted, id)
	return err
}

const markWorkflowRunTerminal = `-- name: MarkWorkflowRunTerminal :exec
UPDATE workflow_runs
SET status = $1, finished_at = NOW()
WHERE id = $2 AND status IN ('pending', 'running')
`

type MarkWorkflowRunTerminalParams struct {
	Status string
	ID     int64
}

func (q *Queries) MarkWorkflowRunTerminal(ctx context.Context, arg MarkWorkflowRunTerminalParams) error {
	_, err := q.db.Exec(ctx, markWorkflowRunTerminal, arg.Status, arg.ID)
	return err
}

const setWorkflowJobContainer = `-- name: SetWorkflowJobContainer :exec
UPDATE workflow_job_runs
SET container_id = $1
WHERE id = $2
`

type SetWorkflowJobContainerParams struct {
	ContainerID pgtype.Text
	ID          int64
}

func (q *Queries) SetWorkflowJobContainer(ctx context.Context, arg SetWorkflowJobContainerParams) error {
	_, err := q.db.Exec(ctx, setWorkflowJobContainer, arg.ContainerID, arg.ID)
	return err
}

const setWorkflowJobOutputs = `-- name: SetWorkflowJobOutputs :exec
UPDATE workflow_job_runs
SET job_outputs_json = $1::jsonb
WHERE id = $2
`

type SetWorkflowJobOutputsParams struct {
	OutputsJson []byte
	ID          int64
}

// Write resolved job outputs after job completion.
func (q *Queries) SetWorkflowJobOutputs(ctx context.Context, arg SetWorkflowJobOutputsParams) error {
	_, err := q.db.Exec(ctx, setWorkflowJobOutputs, arg.OutputsJson, arg.ID)
	return err
}

const setWorkflowJobStepOutputs = `-- name: SetWorkflowJobStepOutputs :exec

UPDATE workflow_job_runs
SET step_outputs_json =
    COALESCE(step_outputs_json, '{}'::jsonb) ||
    jsonb_build_object($1::text, $2::jsonb)
WHERE id = $3
`

type SetWorkflowJobStepOutputsParams struct {
	StepID      string
	OutputsJson []byte
	ID          int64
}

// ---- step and job outputs ----
// Merge a step's outputs into the job's step_outputs_json column.
// Uses jsonb_set with concatenation to merge the step-level map.
// step_id is cast to text because jsonb_build_object takes "any"-typed
// arguments, so a bare parameter leaves Postgres unable to infer the type
// (SQLSTATE 42P18: could not determine data type of parameter $1).
func (q *Queries) SetWorkflowJobStepOutputs(ctx context.Context, arg SetWorkflowJobStepOutputsParams) error {
	_, err := q.db.Exec(ctx, setWorkflowJobStepOutputs, arg.StepID, arg.OutputsJson, arg.ID)
	return err
}

const setWorkflowRunActor = `-- name: SetWorkflowRunActor :exec
UPDATE workflow_runs
SET run_actor_kind = $1,
    run_actor_user_id = $2,
    run_actor_role_key = $3,
    run_actor_workflow_run_id = $4,
    run_actor_display_name = $5
WHERE id = $6
`

type SetWorkflowRunActorParams struct {
	RunActorKind          string
	RunActorUserID        pgtype.Int8
	RunActorRoleKey       string
	RunActorWorkflowRunID pgtype.Int8
	RunActorDisplayName   string
	ID                    int64
}

func (q *Queries) SetWorkflowRunActor(ctx context.Context, arg SetWorkflowRunActorParams) error {
	_, err := q.db.Exec(ctx, setWorkflowRunActor,
		arg.RunActorKind,
		arg.RunActorUserID,
		arg.RunActorRoleKey,
		arg.RunActorWorkflowRunID,
		arg.RunActorDisplayName,
		arg.ID,
	)
	return err
}

const skipRemainingWorkflowJobs = `-- name: SkipRemainingWorkflowJobs :exec
UPDATE workflow_job_runs
SET status = 'skipped', finished_at = NOW()
WHERE workflow_run_id = $1
  AND status = 'pending'
  AND sequence_index > $2
`

type SkipRemainingWorkflowJobsParams struct {
	WorkflowRunID      int64
	AfterSequenceIndex int32
}

func (q *Queries) SkipRemainingWorkflowJobs(ctx context.Context, arg SkipRemainingWorkflowJobsParams) error {
	_, err := q.db.Exec(ctx, skipRemainingWorkflowJobs, arg.WorkflowRunID, arg.AfterSequenceIndex)
	return err
}
