// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package reposilencedb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RepoSilenceAudit struct {
	ID        int64
	RepoID    int64
	Event     string
	Source    string
	ActorID   pgtype.Int8
	SessionID pgtype.Int8
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

type RepoSilenceOverride struct {
	SessionID int64
	RepoID    int64
	GrantedBy int64
	Reason    string
	ExpiresAt pgtype.Timestamptz
	GrantedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type RepoSilenceState struct {
	RepoID         int64
	Active         bool
	Source         string
	SourceRef      string
	EnteredAt      pgtype.Timestamptz
	ExpectedExitAt pgtype.Timestamptz
	Reason         string
	UpdatedAt      pgtype.Timestamptz
}
