// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package reposilencedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeOverride = `-- name: ActiveOverride :one
SELECT session_id, repo_id, granted_by, reason, expires_at,
       granted_at, revoked_at
FROM repo_silence_overrides
WHERE session_id = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) ActiveOverride(ctx context.Context, sessionID int64) (RepoSilenceOverride, error) {
	row := q.db.QueryRow(ctx, activeOverride, sessionID)
	var i RepoSilenceOverride
	err := row.Scan(
		&i.SessionID,
		&i.RepoID,
		&i.GrantedBy,
		&i.Reason,
		&i.ExpiresAt,
		&i.GrantedAt,
		&i.RevokedAt,
	)
	return i, err
}

const appendAudit = `-- name: AppendAudit :exec
INSERT INTO repo_silence_audit
    (repo_id, event, source, actor_id, session_id, payload)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type AppendAuditParams struct {
	RepoID    int64
	Event     string
	Source    string
	ActorID   pgtype.Int8
	SessionID pgtype.Int8
	Payload   []byte
}

func (q *Queries) AppendAudit(ctx context.Context, arg AppendAuditParams) error {
	_, err := q.db.Exec(ctx, appendAudit,
		arg.RepoID,
		arg.Event,
		arg.Source,
		arg.ActorID,
		arg.SessionID,
		arg.Payload,
	)
	return err
}

const getState = `-- name: GetState :one
SELECT repo_id, active, source, source_ref, entered_at,
       expected_exit_at, reason, updated_at
FROM repo_silence_state
WHERE repo_id = $1
`

func (q *Queries) GetState(ctx context.Context, repoID int64) (RepoSilenceState, error) {
	row := q.db.QueryRow(ctx, getState, repoID)
	var i RepoSilenceState
	err := row.Scan(
		&i.RepoID,
		&i.Active,
		&i.Source,
		&i.SourceRef,
		&i.EnteredAt,
		&i.ExpectedExitAt,
		&i.Reason,
		&i.UpdatedAt,
	)
	return i, err
}

const grantOverride = `-- name: GrantOverride :exec
INSERT INTO repo_silence_overrides
    (session_id, repo_id, granted_by, reason, expires_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (session_id) DO UPDATE SET
    repo_id    = EXCLUDED.repo_id,
    granted_by = EXCLUDED.granted_by,
    reason     = EXCLUDED.reason,
    expires_at = EXCLUDED.expires_at,
    granted_at = now(),
    revoked_at = NULL
`

type GrantOverrideParams struct {
	SessionID int64
	RepoID    int64
	GrantedBy int64
	Reason    string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) GrantOverride(ctx context.Context, arg GrantOverrideParams) error {
	_, err := q.db.Exec(ctx, grantOverride,
		arg.SessionID,
		arg.RepoID,
		arg.GrantedBy,
		arg.Reason,
		arg.ExpiresAt,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT id, repo_id, event, source, actor_id, session_id,
       payload, created_at
FROM repo_silence_audit
WHERE repo_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAuditParams struct {
	RepoID int64
	Limit  int32
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]RepoSilenceAudit, error) {
	rows, err := q.db.Query(ctx, listAudit, arg.RepoID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RepoSilenceAudit{}
	for rows.Next() {
		var i RepoSilenceAudit
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Event,
			&i.Source,
			&i.ActorID,
			&i.SessionID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverrides = `-- name: ListOverrides :many
SELECT session_id, repo_id, granted_by, reason, expires_at,
       granted_at, revoked_at
FROM repo_silence_overrides
WHERE repo_id = $1
  AND revoked_at IS NULL
ORDER BY granted_at DESC
`

func (q *Queries) ListOverrides(ctx context.Context, repoID int64) ([]RepoSilenceOverride, error) {
	rows, err := q.db.Query(ctx, listOverrides, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RepoSilenceOverride{}
	for rows.Next() {
		var i RepoSilenceOverride
		if err := rows.Scan(
			&i.SessionID,
			&i.RepoID,
			&i.GrantedBy,
			&i.Reason,
			&i.ExpiresAt,
			&i.GrantedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOverride = `-- name: RevokeOverride :exec
UPDATE repo_silence_overrides
SET revoked_at = now()
WHERE session_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeOverride(ctx context.Context, sessionID int64) error {
	_, err := q.db.Exec(ctx, revokeOverride, sessionID)
	return err
}

const updateState = `-- name: UpdateState :execrows
UPDATE repo_silence_state
SET active           = $1,
    source           = $2,
    source_ref       = $3,
    entered_at       = $4,
    expected_exit_at = $5,
    reason           = $6,
    updated_at       = now()
WHERE repo_id = $7
  AND updated_at = $8
`

type UpdateStateParams struct {
	Active           bool
	Source           string
	SourceRef        string
	EnteredAt        pgtype.Timestamptz
	ExpectedExitAt   pgtype.Timestamptz
	Reason           string
	RepoID           int64
	UpdatedAtWitness pgtype.Timestamptz
}

func (q *Queries) UpdateState(ctx context.Context, arg UpdateStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateState,
		arg.Active,
		arg.Source,
		arg.SourceRef,
		arg.EnteredAt,
		arg.ExpectedExitAt,
		arg.Reason,
		arg.RepoID,
		arg.UpdatedAtWitness,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertState = `-- name: UpsertState :exec
INSERT INTO repo_silence_state
    (repo_id, active, source, source_ref, entered_at,
     expected_exit_at, reason, updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    now()
)
ON CONFLICT (repo_id) DO UPDATE SET
    active           = EXCLUDED.active,
    source           = EXCLUDED.source,
    source_ref       = EXCLUDED.source_ref,
    entered_at       = EXCLUDED.entered_at,
    expected_exit_at = EXCLUDED.expected_exit_at,
    reason           = EXCLUDED.reason,
    updated_at       = now()
`

type UpsertStateParams struct {
	RepoID         int64
	Active         bool
	Source         string
	SourceRef      string
	EnteredAt      pgtype.Timestamptz
	ExpectedExitAt pgtype.Timestamptz
	Reason         string
}

func (q *Queries) UpsertState(ctx context.Context, arg UpsertStateParams) error {
	_, err := q.db.Exec(ctx, upsertState,
		arg.RepoID,
		arg.Active,
		arg.Source,
		arg.SourceRef,
		arg.EnteredAt,
		arg.ExpectedExitAt,
		arg.Reason,
	)
	return err
}
