// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package llmproviderdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGroupsByName = `-- name: CountGroupsByName :one
SELECT COUNT(*)::BIGINT FROM llm_model_groups WHERE name = $1
`

func (q *Queries) CountGroupsByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupsByName, name)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countModelsByName = `-- name: CountModelsByName :one
SELECT COUNT(*)::BIGINT FROM llm_models WHERE name = $1
`

func (q *Queries) CountModelsByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, countModelsByName, name)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUsage = `-- name: CountUsage :one
SELECT COUNT(*)::BIGINT
FROM llm_usage_log u
WHERE ($1::BIGINT IS NULL OR u.provider_id = $1)
  AND ($2::TIMESTAMPTZ IS NULL OR u.created_at >= $2)
`

type CountUsageParams struct {
	ProviderID pgtype.Int8
	Since      pgtype.Timestamptz
}

// Mirrors ListUsage's WHERE clause so the admin usage page can render the
// total row count alongside the paged window.
func (q *Queries) CountUsage(ctx context.Context, arg CountUsageParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsage, arg.ProviderID, arg.Since)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createGroup = `-- name: CreateGroup :one

INSERT INTO llm_model_groups (name, description, actor_id)
VALUES ($1, $2, $3)
RETURNING id, name, description, actor_id, created_at, updated_at
`

type CreateGroupParams struct {
	Name        string
	Description string
	ActorID     int64
}

// ---- model groups ----
func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (LlmModelGroup, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.Name, arg.Description, arg.ActorID)
	var i LlmModelGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ActorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createModel = `-- name: CreateModel :one

INSERT INTO llm_models (
    name, display_name, context_window, max_output_tokens,
    vision, reasoning, reasoning_effort_map, group_id, actor_id
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9
)
RETURNING id, name, display_name, context_window, max_output_tokens, vision, reasoning, reasoning_effort_map, group_id, actor_id, created_at, updated_at
`

type CreateModelParams struct {
	Name               string
	DisplayName        string
	ContextWindow      int32
	MaxOutputTokens    int32
	Vision             bool
	Reasoning          bool
	ReasoningEffortMap []byte
	GroupID            int64
	ActorID            int64
}

// ---- llm models ----
func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) (LlmModel, error) {
	row := q.db.QueryRow(ctx, createModel,
		arg.Name,
		arg.DisplayName,
		arg.ContextWindow,
		arg.MaxOutputTokens,
		arg.Vision,
		arg.Reasoning,
		arg.ReasoningEffortMap,
		arg.GroupID,
		arg.ActorID,
	)
	var i LlmModel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.Vision,
		&i.Reasoning,
		&i.ReasoningEffortMap,
		&i.GroupID,
		&i.ActorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProvider = `-- name: CreateProvider :one
INSERT INTO llm_providers (
    name, type, base_url, api_key_encrypted, allowed_models, actor_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, name, type, base_url, api_key_encrypted, allowed_models, created_at, updated_at, disabled, actor_id
`

type CreateProviderParams struct {
	Name            string
	Type            string
	BaseUrl         string
	ApiKeyEncrypted string
	AllowedModels   []string
	ActorID         int64
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.Name,
		arg.Type,
		arg.BaseUrl,
		arg.ApiKeyEncrypted,
		arg.AllowedModels,
		arg.ActorID,
	)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKeyEncrypted,
		&i.AllowedModels,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Disabled,
		&i.ActorID,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :execrows
DELETE FROM llm_model_groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteModel = `-- name: DeleteModel :execrows
DELETE FROM llm_models WHERE id = $1
`

func (q *Queries) DeleteModel(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteModel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProvider = `-- name: DeleteProvider :execrows
DELETE FROM llm_providers WHERE id = $1
`

func (q *Queries) DeleteProvider(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProvider, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUsageBefore = `-- name: DeleteUsageBefore :execrows
DELETE FROM llm_usage_log WHERE created_at < $1
`

// Hard-deletes usage-log rows whose created_at is strictly before :cutoff.
// Called by the background reaper (service/reaper.go); not exposed through
// the domain.Repo interface or the admin handler.
func (q *Queries) DeleteUsageBefore(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUsageBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const exportUsageCSV = `-- name: ExportUsageCSV :many
SELECT u.id, u.session_id, u.provider_id, u.model,
       u.prompt_tokens, u.completion_tokens, u.total_tokens,
       u.latency_ms, u.status_code, u.error_message, u.request_path,
       u.created_at,
       p.name AS provider_name
FROM llm_usage_log u
JOIN llm_providers p ON p.id = u.provider_id
WHERE ($1::BIGINT IS NULL OR u.provider_id = $1)
  AND ($2::TIMESTAMPTZ IS NULL OR u.created_at >= $2)
ORDER BY u.created_at DESC
LIMIT $4
OFFSET $3
`

type ExportUsageCSVParams struct {
	ProviderID pgtype.Int8
	Since      pgtype.Timestamptz
	Off        int32
	Lim        int32
}

type ExportUsageCSVRow struct {
	ID               int64
	SessionID        pgtype.Int8
	ProviderID       int64
	Model            string
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	LatencyMs        int32
	StatusCode       int32
	ErrorMessage     string
	RequestPath      string
	CreatedAt        pgtype.Timestamptz
	ProviderName     string
}

// Page through the usage log in small chunks so the zip writer can stream
// rows without holding the whole export in memory.
func (q *Queries) ExportUsageCSV(ctx context.Context, arg ExportUsageCSVParams) ([]ExportUsageCSVRow, error) {
	rows, err := q.db.Query(ctx, exportUsageCSV,
		arg.ProviderID,
		arg.Since,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportUsageCSVRow{}
	for rows.Next() {
		var i ExportUsageCSVRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ProviderID,
			&i.Model,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.LatencyMs,
			&i.StatusCode,
			&i.ErrorMessage,
			&i.RequestPath,
			&i.CreatedAt,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportUsageJSONL = `-- name: ExportUsageJSONL :many
SELECT u.id, u.session_id, u.provider_id, u.model,
       u.prompt_tokens, u.completion_tokens, u.total_tokens,
       u.latency_ms, u.status_code, u.error_message, u.request_path,
       u.created_at, u.request_body, u.response_body,
       p.name AS provider_name
FROM llm_usage_log u
JOIN llm_providers p ON p.id = u.provider_id
WHERE ($1::BIGINT IS NULL OR u.provider_id = $1)
  AND ($2::TIMESTAMPTZ IS NULL OR u.created_at >= $2)
ORDER BY u.created_at DESC
LIMIT $4
OFFSET $3
`

type ExportUsageJSONLParams struct {
	ProviderID pgtype.Int8
	Since      pgtype.Timestamptz
	Off        int32
	Lim        int32
}

type ExportUsageJSONLRow struct {
	ID               int64
	SessionID        pgtype.Int8
	ProviderID       int64
	Model            string
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	LatencyMs        int32
	StatusCode       int32
	ErrorMessage     string
	RequestPath      string
	CreatedAt        pgtype.Timestamptz
	RequestBody      string
	ResponseBody     string
	ProviderName     string
}

// Page through the full usage log in small chunks so JSONL export can
// stream request_body / response_body without loading the whole table.
func (q *Queries) ExportUsageJSONL(ctx context.Context, arg ExportUsageJSONLParams) ([]ExportUsageJSONLRow, error) {
	rows, err := q.db.Query(ctx, exportUsageJSONL,
		arg.ProviderID,
		arg.Since,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportUsageJSONLRow{}
	for rows.Next() {
		var i ExportUsageJSONLRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ProviderID,
			&i.Model,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.LatencyMs,
			&i.StatusCode,
			&i.ErrorMessage,
			&i.RequestPath,
			&i.CreatedAt,
			&i.RequestBody,
			&i.ResponseBody,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, description, actor_id, created_at, updated_at FROM llm_model_groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id int64) (LlmModelGroup, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i LlmModelGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ActorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT id, name, description, actor_id, created_at, updated_at FROM llm_model_groups WHERE name = $1
`

func (q *Queries) GetGroupByName(ctx context.Context, name string) (LlmModelGroup, error) {
	row := q.db.QueryRow(ctx, getGroupByName, name)
	var i LlmModelGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ActorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT
    m.id, m.group_id, m.provider_id,
    p.name AS provider_name,
    m.model, m.priority,
    m.manual_disabled, m.auto_disabled_until, m.backoff_step,
    m.last_failure_at, m.last_failure_msg,
    m.last_success_at, m.last_checked_at,
    p.disabled AS provider_disabled,
    m.created_at, m.updated_at
FROM llm_model_group_members m
JOIN llm_providers p ON p.id = m.provider_id
WHERE m.id = $1
`

type GetMemberByIDRow struct {
	ID                int64
	GroupID           int64
	ProviderID        int64
	ProviderName      string
	Model             string
	Priority          int32
	ManualDisabled    bool
	AutoDisabledUntil pgtype.Timestamptz
	BackoffStep       int32
	LastFailureAt     pgtype.Timestamptz
	LastFailureMsg    string
	LastSuccessAt     pgtype.Timestamptz
	LastCheckedAt     pgtype.Timestamptz
	ProviderDisabled  bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetMemberByID(ctx context.Context, id int64) (GetMemberByIDRow, error) {
	row := q.db.QueryRow(ctx, getMemberByID, id)
	var i GetMemberByIDRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ProviderID,
		&i.ProviderName,
		&i.Model,
		&i.Priority,
		&i.ManualDisabled,
		&i.AutoDisabledUntil,
		&i.BackoffStep,
		&i.LastFailureAt,
		&i.LastFailureMsg,
		&i.LastSuccessAt,
		&i.LastCheckedAt,
		&i.ProviderDisabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelByID = `-- name: GetModelByID :one
SELECT id, name, display_name, context_window, max_output_tokens, vision, reasoning, reasoning_effort_map, group_id, actor_id, created_at, updated_at FROM llm_models WHERE id = $1
`

func (q *Queries) GetModelByID(ctx context.Context, id int64) (LlmModel, error) {
	row := q.db.QueryRow(ctx, getModelByID, id)
	var i LlmModel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.Vision,
		&i.Reasoning,
		&i.ReasoningEffortMap,
		&i.GroupID,
		&i.ActorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelByName = `-- name: GetModelByName :one
SELECT id, name, display_name, context_window, max_output_tokens, vision, reasoning, reasoning_effort_map, group_id, actor_id, created_at, updated_at FROM llm_models WHERE name = $1
`

func (q *Queries) GetModelByName(ctx context.Context, name string) (LlmModel, error) {
	row := q.db.QueryRow(ctx, getModelByName, name)
	var i LlmModel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.Vision,
		&i.Reasoning,
		&i.ReasoningEffortMap,
		&i.GroupID,
		&i.ActorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, name, type, base_url, api_key_encrypted, allowed_models, created_at, updated_at, disabled, actor_id FROM llm_providers WHERE id = $1
`

func (q *Queries) GetProviderByID(ctx context.Context, id int64) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKeyEncrypted,
		&i.AllowedModels,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Disabled,
		&i.ActorID,
	)
	return i, err
}

const getProviderByName = `-- name: GetProviderByName :one
SELECT id, name, type, base_url, api_key_encrypted, allowed_models, created_at, updated_at, disabled, actor_id FROM llm_providers WHERE name = $1
`

func (q *Queries) GetProviderByName(ctx context.Context, name string) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, getProviderByName, name)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKeyEncrypted,
		&i.AllowedModels,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Disabled,
		&i.ActorID,
	)
	return i, err
}

const getUsageByID = `-- name: GetUsageByID :one
SELECT u.id, u.session_id, u.provider_id, u.model, u.prompt_tokens, u.completion_tokens, u.total_tokens, u.latency_ms, u.status_code, u.error_message, u.request_path, u.created_at, u.request_body, u.response_body, p.name AS provider_name
FROM llm_usage_log u
JOIN llm_providers p ON p.id = u.provider_id
WHERE u.id = $1
`

type GetUsageByIDRow struct {
	ID               int64
	SessionID        pgtype.Int8
	ProviderID       int64
	Model            string
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	LatencyMs        int32
	StatusCode       int32
	ErrorMessage     string
	RequestPath      string
	CreatedAt        pgtype.Timestamptz
	RequestBody      string
	ResponseBody     string
	ProviderName     string
}

// Single-row detail query that includes the large body columns the list
// endpoint deliberately omits. Used by the admin detail popup.
func (q *Queries) GetUsageByID(ctx context.Context, id int64) (GetUsageByIDRow, error) {
	row := q.db.QueryRow(ctx, getUsageByID, id)
	var i GetUsageByIDRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ProviderID,
		&i.Model,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.LatencyMs,
		&i.StatusCode,
		&i.ErrorMessage,
		&i.RequestPath,
		&i.CreatedAt,
		&i.RequestBody,
		&i.ResponseBody,
		&i.ProviderName,
	)
	return i, err
}

const insertMember = `-- name: InsertMember :exec
INSERT INTO llm_model_group_members (
    group_id, provider_id, model, priority
) VALUES (
    $1, $2, $3, $4
)
`

type InsertMemberParams struct {
	GroupID    int64
	ProviderID int64
	Model      string
	Priority   int32
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) error {
	_, err := q.db.Exec(ctx, insertMember,
		arg.GroupID,
		arg.ProviderID,
		arg.Model,
		arg.Priority,
	)
	return err
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, description, actor_id, created_at, updated_at FROM llm_model_groups ORDER BY name ASC
`

func (q *Queries) ListGroups(ctx context.Context) ([]LlmModelGroup, error) {
	rows, err := q.db.Query(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmModelGroup{}
	for rows.Next() {
		var i LlmModelGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ActorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersByGroupID = `-- name: ListMembersByGroupID :many
SELECT
    m.id, m.group_id, m.provider_id,
    p.name AS provider_name,
    m.model, m.priority,
    m.manual_disabled, m.auto_disabled_until, m.backoff_step,
    m.last_failure_at, m.last_failure_msg,
    m.last_success_at, m.last_checked_at,
    p.disabled AS provider_disabled,
    m.created_at, m.updated_at
FROM llm_model_group_members m
JOIN llm_providers p ON p.id = m.provider_id
WHERE m.group_id = $1
ORDER BY m.priority ASC
`

type ListMembersByGroupIDRow struct {
	ID                int64
	GroupID           int64
	ProviderID        int64
	ProviderName      string
	Model             string
	Priority          int32
	ManualDisabled    bool
	AutoDisabledUntil pgtype.Timestamptz
	BackoffStep       int32
	LastFailureAt     pgtype.Timestamptz
	LastFailureMsg    string
	LastSuccessAt     pgtype.Timestamptz
	LastCheckedAt     pgtype.Timestamptz
	ProviderDisabled  bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

// Join provider columns so the service layer can compute MemberHealth
// without a separate provider query per member.
func (q *Queries) ListMembersByGroupID(ctx context.Context, groupID int64) ([]ListMembersByGroupIDRow, error) {
	rows, err := q.db.Query(ctx, listMembersByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersByGroupIDRow{}
	for rows.Next() {
		var i ListMembersByGroupIDRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.ProviderID,
			&i.ProviderName,
			&i.Model,
			&i.Priority,
			&i.ManualDisabled,
			&i.AutoDisabledUntil,
			&i.BackoffStep,
			&i.LastFailureAt,
			&i.LastFailureMsg,
			&i.LastSuccessAt,
			&i.LastCheckedAt,
			&i.ProviderDisabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModels = `-- name: ListModels :many
SELECT id, name, display_name, context_window, max_output_tokens, vision, reasoning, reasoning_effort_map, group_id, actor_id, created_at, updated_at FROM llm_models ORDER BY name ASC
`

func (q *Queries) ListModels(ctx context.Context) ([]LlmModel, error) {
	rows, err := q.db.Query(ctx, listModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmModel{}
	for rows.Next() {
		var i LlmModel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.Vision,
			&i.Reasoning,
			&i.ReasoningEffortMap,
			&i.GroupID,
			&i.ActorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviders = `-- name: ListProviders :many
SELECT id, name, type, base_url, api_key_encrypted, allowed_models, created_at, updated_at, disabled, actor_id FROM llm_providers ORDER BY name ASC
`

func (q *Queries) ListProviders(ctx context.Context) ([]LlmProvider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmProvider{}
	for rows.Next() {
		var i LlmProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.BaseUrl,
			&i.ApiKeyEncrypted,
			&i.AllowedModels,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Disabled,
			&i.ActorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsage = `-- name: ListUsage :many
SELECT u.id, u.session_id, u.provider_id, u.model,
       u.prompt_tokens, u.completion_tokens, u.total_tokens,
       u.latency_ms, u.status_code, u.error_message, u.request_path,
       u.created_at,
       p.name AS provider_name
FROM llm_usage_log u
JOIN llm_providers p ON p.id = u.provider_id
WHERE ($1::BIGINT IS NULL OR u.provider_id = $1)
  AND ($2::TIMESTAMPTZ IS NULL OR u.created_at >= $2)
ORDER BY u.created_at DESC
LIMIT $4
OFFSET $3
`

type ListUsageParams struct {
	ProviderID pgtype.Int8
	Since      pgtype.Timestamptz
	Off        int32
	Lim        int32
}

type ListUsageRow struct {
	ID               int64
	SessionID        pgtype.Int8
	ProviderID       int64
	Model            string
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	LatencyMs        int32
	StatusCode       int32
	ErrorMessage     string
	RequestPath      string
	CreatedAt        pgtype.Timestamptz
	ProviderName     string
}

// Explicit column list excludes request_body/response_body so the list
// query stays fast — the detail endpoint (GetUsageByID) carries the large
// body columns on a single row.
func (q *Queries) ListUsage(ctx context.Context, arg ListUsageParams) ([]ListUsageRow, error) {
	rows, err := q.db.Query(ctx, listUsage,
		arg.ProviderID,
		arg.Since,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsageRow{}
	for rows.Next() {
		var i ListUsageRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ProviderID,
			&i.Model,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.LatencyMs,
			&i.StatusCode,
			&i.ErrorMessage,
			&i.RequestPath,
			&i.CreatedAt,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordUsage = `-- name: RecordUsage :exec
INSERT INTO llm_usage_log (
    session_id, provider_id, model,
    prompt_tokens, completion_tokens, total_tokens,
    latency_ms, status_code, error_message, request_path,
    request_body, response_body
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
`

type RecordUsageParams struct {
	SessionID        pgtype.Int8
	ProviderID       int64
	Model            string
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	LatencyMs        int32
	StatusCode       int32
	ErrorMessage     string
	RequestPath      string
	RequestBody      string
	ResponseBody     string
}

func (q *Queries) RecordUsage(ctx context.Context, arg RecordUsageParams) error {
	_, err := q.db.Exec(ctx, recordUsage,
		arg.SessionID,
		arg.ProviderID,
		arg.Model,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.LatencyMs,
		arg.StatusCode,
		arg.ErrorMessage,
		arg.RequestPath,
		arg.RequestBody,
		arg.ResponseBody,
	)
	return err
}

const replaceMembers = `-- name: ReplaceMembers :exec

DELETE FROM llm_model_group_members WHERE group_id = $1
`

// ---- model group members ----
// Delete all existing members for the group, then insert the new list.
// Callers must wrap both in a transaction.
func (q *Queries) ReplaceMembers(ctx context.Context, groupID int64) error {
	_, err := q.db.Exec(ctx, replaceMembers, groupID)
	return err
}

const setProviderDisabled = `-- name: SetProviderDisabled :one
UPDATE llm_providers SET
    disabled   = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, name, type, base_url, api_key_encrypted, allowed_models, created_at, updated_at, disabled, actor_id
`

type SetProviderDisabledParams struct {
	Disabled bool
	ID       int64
}

// Dedicated flip so the admin UI can toggle enable/disable without having
// to round-trip the full UpdateProvider payload (and without risking a
// stale base_url / allowed_models clobber).
func (q *Queries) SetProviderDisabled(ctx context.Context, arg SetProviderDisabledParams) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, setProviderDisabled, arg.Disabled, arg.ID)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKeyEncrypted,
		&i.AllowedModels,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Disabled,
		&i.ActorID,
	)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE llm_model_groups SET
    description = $1,
    updated_at  = NOW()
WHERE id = $2
RETURNING id, name, description, actor_id, created_at, updated_at
`

type UpdateGroupParams struct {
	Description string
	ID          int64
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (LlmModelGroup, error) {
	row := q.db.QueryRow(ctx, updateGroup, arg.Description, arg.ID)
	var i LlmModelGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ActorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMemberHealth = `-- name: UpdateMemberHealth :execrows
UPDATE llm_model_group_members SET
    manual_disabled     = COALESCE($1, manual_disabled),
    auto_disabled_until = CASE WHEN $2::TIMESTAMPTZ IS NOT NULL
                               THEN $2
                               WHEN $3::BOOLEAN
                               THEN NULL
                               ELSE auto_disabled_until END,
    backoff_step        = COALESCE($4, backoff_step),
    last_failure_at     = COALESCE($5, last_failure_at),
    last_failure_msg    = COALESCE($6, last_failure_msg),
    last_success_at     = COALESCE($7, last_success_at),
    last_checked_at     = COALESCE($8, last_checked_at),
    updated_at          = NOW()
WHERE id = $9
`

type UpdateMemberHealthParams struct {
	ManualDisabled        pgtype.Bool
	AutoDisabledUntil     pgtype.Timestamptz
	AutoDisabledUntilNull pgtype.Bool
	BackoffStep           pgtype.Int4
	LastFailureAt         pgtype.Timestamptz
	LastFailureMsg        pgtype.Text
	LastSuccessAt         pgtype.Timestamptz
	LastCheckedAt         pgtype.Timestamptz
	ID                    int64
}

// Atomically update health fields. Each field is only touched when its
// corresponding parameter is non-null (sqlc.narg). This single-statement
// pattern avoids a read-then-write race on backoff_step.
func (q *Queries) UpdateMemberHealth(ctx context.Context, arg UpdateMemberHealthParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMemberHealth,
		arg.ManualDisabled,
		arg.AutoDisabledUntil,
		arg.AutoDisabledUntilNull,
		arg.BackoffStep,
		arg.LastFailureAt,
		arg.LastFailureMsg,
		arg.LastSuccessAt,
		arg.LastCheckedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModel = `-- name: UpdateModel :one
UPDATE llm_models SET
    display_name         = $1,
    context_window       = $2,
    max_output_tokens    = $3,
    vision               = $4,
    reasoning            = $5,
    reasoning_effort_map = $6,
    updated_at           = NOW()
WHERE id = $7
RETURNING id, name, display_name, context_window, max_output_tokens, vision, reasoning, reasoning_effort_map, group_id, actor_id, created_at, updated_at
`

type UpdateModelParams struct {
	DisplayName        string
	ContextWindow      int32
	MaxOutputTokens    int32
	Vision             bool
	Reasoning          bool
	ReasoningEffortMap []byte
	ID                 int64
}

func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) (LlmModel, error) {
	row := q.db.QueryRow(ctx, updateModel,
		arg.DisplayName,
		arg.ContextWindow,
		arg.MaxOutputTokens,
		arg.Vision,
		arg.Reasoning,
		arg.ReasoningEffortMap,
		arg.ID,
	)
	var i LlmModel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.Vision,
		&i.Reasoning,
		&i.ReasoningEffortMap,
		&i.GroupID,
		&i.ActorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE llm_providers SET
    base_url          = $1,
    api_key_encrypted = COALESCE($2, api_key_encrypted),
    allowed_models    = $3,
    disabled          = $4,
    updated_at        = NOW()
WHERE id = $5
RETURNING id, name, type, base_url, api_key_encrypted, allowed_models, created_at, updated_at, disabled, actor_id
`

type UpdateProviderParams struct {
	BaseUrl         string
	ApiKeyEncrypted pgtype.Text
	AllowedModels   []string
	Disabled        bool
	ID              int64
}

// sqlc.narg('api_key_encrypted') makes the parameter nullable; COALESCE
// keeps the stored sealed blob when the caller passes NULL (= no rotation).
func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.BaseUrl,
		arg.ApiKeyEncrypted,
		arg.AllowedModels,
		arg.Disabled,
		arg.ID,
	)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKeyEncrypted,
		&i.AllowedModels,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Disabled,
		&i.ActorID,
	)
	return i, err
}
